# Generated by Django 5.0 on 2023-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0002_exercises_sports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Injuries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField()),
                ("title", models.TextField()),
                ("about", models.TextField()),
                ("link", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="sports",
            old_name="video",
            new_name="image",
        ),
    ]
