# Generated by Django 5.0 on 2023-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0003_injuries_rename_video_sports_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuries",
            name="background",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sports",
            name="background",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
