# Generated by Django 5.0 on 2023-12-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0004_injuries_background_sports_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="sports",
            name="section",
            field=models.TextField(default="sport"),
            preserve_default=False,
        ),
    ]
