# Generated by Django 5.0 on 2023-12-30 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0005_sports_section"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calories",
        ),
        migrations.DeleteModel(
            name="Exercises",
        ),
        migrations.DeleteModel(
            name="Injuries",
        ),
    ]
