# Generated by Django 5.0 on 2023-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0006_delete_calories_delete_exercises_delete_injuries"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_date", models.DateField()),
                ("exercise_value", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
