# Generated by Django 5.0 on 2024-01-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0007_exercises"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_name", models.DateField()),
                ("meal_kcal", models.IntegerField()),
                ("meal_measure", models.IntegerField()),
                ("meal_weight", models.IntegerField()),
                ("meal_fat", models.IntegerField()),
                ("meal_carbo", models.IntegerField()),
                ("meal_protein", models.IntegerField()),
            ],
        ),
    ]
