# Generated by Django 5.0 on 2024-01-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0008_meals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meals",
            name="meal_name",
            field=models.TextField(),
        ),
    ]
