# Generated by Django 5.0 on 2024-01-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0009_alter_meals_meal_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meals",
            name="meal_measure",
            field=models.TextField(),
        ),
    ]
