# Generated by Django 5.0 on 2024-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0010_alter_meals_meal_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meals",
            name="meal_carbo",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="meals",
            name="meal_fat",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="meals",
            name="meal_kcal",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="meals",
            name="meal_protein",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="meals",
            name="meal_weight",
            field=models.CharField(max_length=255),
        ),
    ]
