# Generated by Django 5.0 on 2024-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0011_alter_meals_meal_carbo_alter_meals_meal_fat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercises",
            name="exercise_value",
            field=models.IntegerField(),
        ),
    ]
