# Generated by Django 5.0 on 2024-01-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0012_alter_exercises_exercise_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meals",
            name="meal_kcal",
            field=models.IntegerField(max_length=255),
        ),
    ]
