# Generated by Django 5.0 on 2024-01-05 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0018_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="dob",
        ),
    ]
