# Generated by Django 5.0 on 2024-01-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0020_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercises",
            name="exercise_type",
            field=models.TextField(default="Hand"),
            preserve_default=False,
        ),
    ]
